Cypress refactor
DouglasNeuroInformatics/OpenDataCapture pull request #737
Opened 2024-03-05 16:18 UTC by david-roper

The following merge request includes:

- A E2E test suite for the OpenDataCapture Web Application
- A mock service worker for mock API calls used in the E2E tests
- Adds data-cy labels to UI elements for future testing purposes

Steps to run the test suite are as follows:

cd /OpenDataCapture/apps/web
pnpm test:dev

Non CLI version
pnpm test

2024-03-05 20:18 UTC, joshunrau requested changes
Why do you force click all buttons? Do not add force to things unless it is necessary (which as far as I understand, should not be the case anywhere here). If it is necessary, please let me know and I will investigate if there is a problem.

Using `cy.wait` is almost always considered an anti-pattern (https://docs.cypress.io/api/commands/wait#Wait-for-an-arbitrary-period-of-milliseconds). Please remove all usages of this, or provide a justification for why it is necessary.

Please avoid getting DOM elements by non-specific attributes (including, but not limited to, class name, type of the element, etc.). It is not obvious what you are getting and this is extremely easy for me, or somebody else, to break. Please prefer getting items by test id, or in the case of forms, name, which will not change between UI updates.

Prefer getting the element by test ID (or equivalent). If you are getting the element by something that could theoretically be duplicated, but in-practice never will (e.g., text content of buttons to select the year), please mention this is a comment. You can make a PR against JSLibs if you need to add test ids to things.

Under no circumstances depend on implementation details of third party libraries for tests. This will almost certainly break from under us at a certain point

2024-03-05 20:18 UTC, joshunrau commented on apps/web/cypress/e2e/tags.cy.ts
> +    cy.get('span[class="ui-selected:font-medium"]')
see overall comments

2024-03-05 20:18 UTC, joshunrau commented on apps/web/cypress/e2e/tags.cy.ts
> +    //deselect the first tag
see overall comments

2024-03-05 20:18 UTC, joshunrau commented on apps/web/cypress/e2e/tags.cy.ts
> +    //check form contains the second tag
see overall comments

2024-03-05 20:18 UTC, joshunrau commented on apps/web/cypress/e2e/tags.cy.ts
> +    //deselect the second tag, select the third tag
see overall comments

2024-03-05 20:18 UTC, joshunrau commented on apps/web/cypress/e2e/tags.cy.ts
> +    //deselect schizo and psychosis from search
see overall comments

2024-03-05 20:18 UTC, joshunrau commented on apps/web/cypress/support/commands.ts
> +Cypress.Commands.add('dragTo', { prevSubject: 'element' }, (subject, targetSelector) => {
This is cool!

2024-03-05 20:18 UTC, joshunrau commented on apps/web/src/features/subjects/components/SubjectLayout.tsx
Great!

2024-03-05 20:18 UTC, joshunrau commented on apps/web/src/test/server/browser.ts
> +import { ManageInstrumentHandlers } from './handlers/instrument-manager.handlers';
Why is this capitalized?

2024-03-05 20:18 UTC, joshunrau commented on apps/web/src/test/server/browser.ts
> +import { SubjectHandlers } from './handlers/subject.handlers';
Why is this capitalized?

2024-03-05 20:18 UTC, joshunrau commented on apps/web/src/test/server/handlers/summary.handlers.ts
> +export const SummaryHandlers = [
Why is this capitalized?

2024-03-05 20:18 UTC, joshunrau commented on apps/web/src/test/server/handlers/visit.handlers.ts
> +export const VisitHandler = [
Why is this capitalized?

2024-03-05 20:18 UTC, joshunrau commented on pnpm-lock.yaml
Please discard these changes. I cannot on GitHub UI.

2024-03-05 20:18 UTC, joshunrau commented on pnpm-lock.yaml
I discarded your changes in package.json (you accepted the wrong changes on merge), but this I can't

2024-03-05 20:47 UTC, david-roper commented on .gitignore
> +data/
fixed

2024-03-05 20:47 UTC, david-roper commented on .gitignore
> +bun.lockb
removed

2024-03-05 20:55 UTC, david-roper commented on apps/web/cypress/e2e/add-visit.cy.ts
> +    cy.get('button[data-cy="add-visit"]').first().click({ force: true });
certain UI elements require force: true to be clicked when they are overlapping another element. 
This scenario the force true was used if ever the add visit modal overlapped the side bar, but not it is unnecessary and removed.

2024-03-05 21:02 UTC, david-roper commented on apps/web/cypress/e2e/add-visit.cy.ts
> +    cy.get('input[class=field-input]').first().type('test');
The DOB input does not currently have a name variable. It is a weird case where it should be clicked to select dates from the dropdown but is considered a "type into input" to activate said dropdown by cypress. Adding a name to the element will make the test more readable.

2024-03-07 15:13 UTC, david-roper commented on apps/web/cypress/e2e/add-visit.cy.ts
> +    cy.wait(500);
replaced with waiting for element to be visible

2024-03-12 15:18 UTC, david-roper reviewed
All comments have now been addressed and resolved in most recent commits

2024-03-12 15:34 UTC, joshunrau approved these changes
much better, thanks

2024-03-12 15:34 UTC, merged